[package]
name = "zaft-js"
version = "0.3.8"
edition = "2024"
description = "Fast fourier transform"
readme = "README.md"
keywords = ["fft", "dft", "discrete", "fourier"]
license = "BSD-3-Clause OR Apache-2.0"
authors = ["Radzivon Bartoshyk"]
documentation = "https://github.com/awxkee/zaft"
categories = ["algorithms", "science"]
homepage = "https://github.com/awxkee/zaft"
repository = "https://github.com/awxkee/zaft"
exclude = ["*.jpg", "/assets", "*.png", "*.sh", "/assets/*", ".github"]
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
zaft = { path = "../", features = ["wasm"] }
wasm-bindgen = "0.2.122"
num-complex = "0.4.6"

[dev-dependencies]
wasm-bindgen-test = "0.3.72"