name: Test SVE

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'dev'

jobs:
  tests_sve:
    name: Tests
    strategy:
      matrix:
        features: [ "", sve ]
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test  --no-default-features --features "${{ matrix.features }}"